[theme]
base = "light"
primaryColor = "#7F56D9"
backgroundColor = "#F6F8FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101828"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

